version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6
    commands:
      - echo "Restaurando pacotes NuGet..."
      - dotnet restore main/FiapCloudGames/FiapCloudGames.sln
  build:
    commands:
      - echo "Compilando a solution em modo Release..."
      - dotnet build main/FiapCloudGames/FiapCloudGames.sln --configuration Release --no-restore
  post_build:
    commands:
      - echo "Preparando deploy..."
      # Exemplo deploy S3 (substitua pelo seu destino real)
      - aws s3 sync ./wwwroot s3://meu-bucket-prod/ --delete

artifacts:
  files:
    - '**/*'
