version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      docker: 24
    commands:
      - echo "Usando .NET 8 e Docker"
      - dotnet --version
      - docker --version
      # Login no ECR (substitua pelo seu URI)
      - $(aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 701604998561.dkr.ecr.sa-east-1.amazonaws.com)

  pre_build:
    commands:
      - echo "Restaurando dependências do projeto..."
      - dotnet restore FiapCloudGames/FiapCloudGames.sln
      - echo "Definindo nome da imagem e tag..."
      - IMAGE_NAME=fcg-app
      - IMAGE_TAG=latest
      - echo "Imagem será construída com a tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Compilando projeto em Release..."
      - dotnet build FiapCloudGames/FiapCloudGames.sln --configuration Release
      - echo "Construindo imagem Docker..."
      - docker build -t $IMAGE_NAME:$IMAGE_TAG -f FiapCloudGames/Dockerfile FiapCloudGames

  post_build:
    commands:
      - echo "Tagging e enviando imagem para o ECR..."
      - docker tag $IMAGE_NAME:$IMAGE_TAG 701604998561.dkr.ecr.sa-east-1.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
      - docker push 701604998561.dkr.ecr.sa-east-1.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
      - echo "Build Docker e push concluídos com sucesso."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
