version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Usando imagem gerenciada com .NET 8 instalado"
      - dotnet --version

  pre_build:
    commands:
      - echo "Restaurando dependências do projeto..."
      - dotnet restore FiapCloudGames/FiapCloudGames.sln

  build:
    commands:
      - echo "Compilando projeto em modo Release..."
      - dotnet build FiapCloudGames/FiapCloudGames.sln --configuration Release

  post_build:
    commands:
      - echo "Build concluído com sucesso."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
