version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Usando .NET 8 e Docker instalados"
      - dotnet --version
      - echo "Detectando branch atual..."
      - |
        if [ -n "$CODEBUILD_WEBHOOK_HEAD_REF" ]; then
          BRANCH_NAME=$(echo "$CODEBUILD_WEBHOOK_HEAD_REF" | sed 's|refs/heads/||')
        elif [ -n "$CODEBUILD_SOURCE_VERSION" ]; then
          BRANCH_NAME=$(echo "$CODEBUILD_SOURCE_VERSION" | sed 's|refs/heads/||')
        elif [ -n "$CODEBUILD_SOURCE_BRANCH" ]; then
          BRANCH_NAME=$(echo "$CODEBUILD_SOURCE_BRANCH" | sed 's|refs/heads/||')
        else
          BRANCH_NAME="unknown"
        fi

        echo "Branch detectada: $BRANCH_NAME"
        echo "export BRANCH_NAME=$BRANCH_NAME" >> ~/.bash_profile

        if [[ "$BRANCH_NAME" != "main" && "$BRANCH_NAME" != "develop" ]]; then
          echo "Erro: Builds só são permitidos nas branches 'main' ou 'develop'."
          exit 1
        fi

      - docker --version
      - |
        source ~/.bash_profile
        if [ "$BRANCH_NAME" = "main" ]; then
          echo "Realizando login no Amazon ECR..."
          aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 701604998561.dkr.ecr.sa-east-1.amazonaws.com
        else
          echo "Branch não é main, pulando login no ECR."
        fi

  pre_build:
    commands:
      - echo "Restaurando dependências do projeto..."
      - dotnet restore FiapCloudGames/FiapCloudGames.sln

  build:
    commands:
      - echo "Compilando projeto em modo Release..."
      - dotnet build FiapCloudGames/FiapCloudGames.sln --configuration Release
      - |
        source ~/.bash_profile
        if [ "$BRANCH_NAME" = "main" ]; then
          echo "Construindo imagem Docker..."
          docker build -t 701604998561.dkr.ecr.sa-east-1.amazonaws.com/fcg-app:latest -f FiapCloudGames/Dockerfile FiapCloudGames
        else
          echo "Branch não é main, pulando build da imagem Docker."
        fi

  post_build:
    commands:
      - |
        source ~/.bash_profile
        if [ "$BRANCH_NAME" = "main" ]; then
          echo "Enviando imagem Docker para o ECR..."
          docker push 701604998561.dkr.ecr.sa-east-1.amazonaws.com/fcg-ap
