-- ========== DROPS DE CONSTRAINTS DE FK ==========



IF OBJECT_ID('FK_PROMOCAO_JOGO', 'F') IS NOT NULL
    ALTER TABLE PROMOCAO DROP CONSTRAINT FK_PROMOCAO_JOGO;
GO

IF OBJECT_ID('FK_PEDIDO_USUARIO', 'F') IS NOT NULL
    ALTER TABLE PEDIDO DROP CONSTRAINT FK_PEDIDO_USUARIO;
GO

IF OBJECT_ID('FK_PEDIDO_JOGO', 'F') IS NOT NULL
    ALTER TABLE PEDIDO DROP CONSTRAINT FK_PEDIDO_JOGO;
GO

IF OBJECT_ID('FK_PEDIDO_PROMOCAO', 'F') IS NOT NULL
    ALTER TABLE PEDIDO DROP CONSTRAINT FK_PEDIDO_PROMOCAO;
GO



-- ========== DROPS DE TABELAS ==========
IF OBJECT_ID('DBO.__EFMigrationsHistory', 'U') IS NOT NULL
    DROP TABLE DBO.__EFMigrationsHistory;
GO

IF OBJECT_ID('DBO.PEDIDO', 'U') IS NOT NULL
    DROP TABLE DBO.PEDIDO;
GO

IF OBJECT_ID('DBO.PROMOCAO', 'U') IS NOT NULL
    DROP TABLE DBO.PROMOCAO;
GO

IF OBJECT_ID('DBO.USUARIO', 'U') IS NOT NULL
    DROP TABLE DBO.USUARIO;
GO

IF OBJECT_ID('DBO.JOGO', 'U') IS NOT NULL
    DROP TABLE DBO.JOGO;
GO

DROP VIEW IF EXISTS VW_PEDIDOS;

-- ========== USUARIO ==========
CREATE TABLE USUARIO (
  ID           INT IDENTITY(1,1)
 ,DATACRIACAO  DATETIME
 ,NOME         VARCHAR(100) COLLATE LATIN1_GENERAL_CI_AI NOT NULL
 ,EMAIL        VARCHAR(100) COLLATE LATIN1_GENERAL_CI_AI NOT NULL
 ,SENHA        VARCHAR(100) COLLATE LATIN1_GENERAL_CI_AI NOT NULL
 ,NIVEL        CHAR(1)      COLLATE LATIN1_GENERAL_CI_AI NOT NULL
 ,CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
  CONSTRAINT UQ_USUARIO_EMAIL UNIQUE (EMAIL)
);
GO

INSERT INTO USUARIO (DATACRIACAO, NOME, EMAIL, SENHA, NIVEL) VALUES ('20240315 08:23:45', 'ADMIN'         , 'admin@fiap.com.br' , 'AAAAAA#1' , 'A');
INSERT INTO USUARIO (DATACRIACAO, NOME, EMAIL, SENHA, NIVEL) VALUES ('20240722 19:10:07', 'MARIA OLIVEIRA', 'maria@uol.com.br'  , 'F7#W1$PK' , 'U');
INSERT INTO USUARIO (DATACRIACAO, NOME, EMAIL, SENHA, NIVEL) VALUES ('20241205 14:55:30', 'PEDRO SOUSA'   , 'pedro@uol.com.br'  , 'M3&HT9*V' , 'U');
INSERT INTO USUARIO (DATACRIACAO, NOME, EMAIL, SENHA, NIVEL) VALUES ('20250310 06:42:18', 'ANA CARLA'     , 'ana@uol.com.br'    , 'Z8!CP5@R' , 'U');
INSERT INTO USUARIO (DATACRIACAO, NOME, EMAIL, SENHA, NIVEL) VALUES ('20241018 22:15:54', 'CARLOS MENDES' , 'carlos@uol.com.br' , 'B4$NK6^Y' , 'U');
INSERT INTO USUARIO (DATACRIACAO, NOME, EMAIL, SENHA, NIVEL) VALUES ('20240830 11:33:09', 'LUCAS FREITAS' , 'lucas@uol.com.br'  , 'D2*QF8#L' , 'U');
INSERT INTO USUARIO (DATACRIACAO, NOME, EMAIL, SENHA, NIVEL) VALUES ('20240607 17:27:38', 'RAFAELA SANTOS', 'rafaela@uol.com.br', 'V1!RW3$C' , 'U');
INSERT INTO USUARIO (DATACRIACAO, NOME, EMAIL, SENHA, NIVEL) VALUES ('20240521 09:44:52', 'FELIPE ALMEIDA', 'felipe@uol.com.br' , 'J6@MG7%X' , 'U');
INSERT INTO USUARIO (DATACRIACAO, NOME, EMAIL, SENHA, NIVEL) VALUES ('20241227 23:59:59', 'PAULA COSTA'   , 'paula@uol.com.br'  , 'S5^ZL0!H' , 'U');
INSERT INTO USUARIO (DATACRIACAO, NOME, EMAIL, SENHA, NIVEL) VALUES ('20240411 03:15:07', 'BRUNO PEREIRA' , 'bruno@uol.com.br'  , 'R9#YD4&F' , 'U');
GO

-- ========== JOGO ==========
CREATE TABLE JOGO (
  ID             INT IDENTITY(1,1)
 ,DATACRIACAO    DATETIME                                  NOT NULL
 ,NOME           VARCHAR(100) COLLATE LATIN1_GENERAL_CI_AI NOT NULL
 ,ANOLANCAMENTO  INT                                       NOT NULL
 ,PRECOBASE      DECIMAL(10,2)                             NOT NULL
 ,CONSTRAINT PK_JOGO PRIMARY KEY (ID)
);
GO


INSERT INTO JOGO ( DATACRIACAO, NOME, ANOLANCAMENTO, PRECOBASE) VALUES ('1981-03-12 10:15:22', 'THE LAST QUEST' , 1981, 59.90);
INSERT INTO JOGO ( DATACRIACAO, NOME, ANOLANCAMENTO, PRECOBASE) VALUES ('1982-07-08 14:42:10', 'SPACE ADVENTURE', 1982, 49.50);
INSERT INTO JOGO ( DATACRIACAO, NOME, ANOLANCAMENTO, PRECOBASE) VALUES ('1983-05-19 09:05:48', 'MYSTERY ISLAND' , 1983, 39.99);
INSERT INTO JOGO ( DATACRIACAO, NOME, ANOLANCAMENTO, PRECOBASE) VALUES ('1984-01-27 16:33:59', 'CYBER RUNNER'   , 1984, 69.90);
INSERT INTO JOGO ( DATACRIACAO, NOME, ANOLANCAMENTO, PRECOBASE) VALUES ('1985-11-03 21:47:03', 'FANTASY WORLD'  , 1985, 29.99);
INSERT INTO JOGO ( DATACRIACAO, NOME, ANOLANCAMENTO, PRECOBASE) VALUES ('1986-08-14 12:20:00', 'RACING FEVER'   , 1986, 44.95);
INSERT INTO JOGO ( DATACRIACAO, NOME, ANOLANCAMENTO, PRECOBASE) VALUES ('1987-02-25 07:58:17', 'ZOMBIE ATTACK'  , 1987, 34.99);
INSERT INTO JOGO ( DATACRIACAO, NOME, ANOLANCAMENTO, PRECOBASE) VALUES ('1988-06-01 19:36:45', 'DRAGON SLAYER'  , 1988, 59.99);
INSERT INTO JOGO ( DATACRIACAO, NOME, ANOLANCAMENTO, PRECOBASE) VALUES ('1989-09-18 05:12:39', 'PUZZLE MASTER'  , 1989, 19.90);
INSERT INTO JOGO ( DATACRIACAO, NOME, ANOLANCAMENTO, PRECOBASE) VALUES ('1990-04-22 23:11:26', 'WARZONE HEROES' , 1990, 74.90);
GO

-- ========== PROMOCAO ==========
CREATE TABLE PROMOCAO (
  ID             INT IDENTITY(1,1)
 ,NOME           VARCHAR(100) COLLATE LATIN1_GENERAL_CI_AI NOT NULL
 ,DATACRIACAO    DATETIME  NOT NULL
 ,DESCONTO       INT       NOT NULL
 ,DATAVALIDADE   DATETIME  NOT NULL
 ,CONSTRAINT PK_PROMOCAO      PRIMARY KEY (ID)
);
GO


INSERT INTO PROMOCAO (DATACRIACAO, NOME, DESCONTO, DATAVALIDADE) VALUES ('2016-01-01 00:00:00','PROMOÇÃO DOS JOGOS 2016',   30, '2016-12-31 23:59:59');
INSERT INTO PROMOCAO (DATACRIACAO, NOME, DESCONTO, DATAVALIDADE) VALUES ('2017-01-01 00:00:00','DESCONTOS GAMER 2017',      25, '2017-12-31 23:59:59');
INSERT INTO PROMOCAO (DATACRIACAO, NOME, DESCONTO, DATAVALIDADE) VALUES ('2018-01-01 00:00:00','OFERTA DE JOGADOR 2018',    15, '2018-12-31 23:59:59');
INSERT INTO PROMOCAO (DATACRIACAO, NOME, DESCONTO, DATAVALIDADE) VALUES ('2019-01-01 00:00:00','ANO GAMER 2019',            33, '2019-12-31 23:59:59');
INSERT INTO PROMOCAO (DATACRIACAO, NOME, DESCONTO, DATAVALIDADE) VALUES ('2020-01-01 00:00:00','SUPER PROMOÇÃO GAMER 2020', 35, '2020-12-31 23:59:59');
INSERT INTO PROMOCAO (DATACRIACAO, NOME, DESCONTO, DATAVALIDADE) VALUES ('2021-01-01 00:00:00','JOGOS EM OFERTA 2021',      20, '2021-12-31 23:59:59');
INSERT INTO PROMOCAO (DATACRIACAO, NOME, DESCONTO, DATAVALIDADE) VALUES ('2022-01-01 00:00:00','SEMANA DO JOGO 2022',       40, '2022-12-31 23:59:59');
INSERT INTO PROMOCAO (DATACRIACAO, NOME, DESCONTO, DATAVALIDADE) VALUES ('2023-01-01 00:00:00','FESTIVAL DOS JOGOS 2023',   25, '2023-12-31 23:59:59');
INSERT INTO PROMOCAO (DATACRIACAO, NOME, DESCONTO, DATAVALIDADE) VALUES ('2024-01-01 00:00:00','EXPLOSÃO GAMER 2024',       50, '2024-12-31 23:59:59');
INSERT INTO PROMOCAO (DATACRIACAO, NOME, DESCONTO, DATAVALIDADE) VALUES ('2025-01-01 00:00:00','PROMOÇÃO CAMPEÃ 2025',      10, '2025-12-31 23:59:59');
GO


-- ========== PEDIDO ==========
CREATE TABLE PEDIDO (
  ID             INT IDENTITY(1,1)
 ,DATACRIACAO    DATETIME          NOT NULL
 ,USUARIOID      INT               NOT NULL
 ,JOGOID         INT               NOT NULL
 ,PROMOCAOID     INT                                       
 ,VLPEDIDO      DECIMAL(10,2)     NOT NULL
 ,VLDESCONTO    DECIMAL(10,2)     NOT NULL
 ,VLPAGO        DECIMAL(10,2)     NOT NULL
 ,CONSTRAINT PK_PEDIDO PRIMARY KEY (ID)
 ,CONSTRAINT FK_PEDIDO_USUARIO  FOREIGN KEY (USUARIOID)  REFERENCES USUARIO  (ID)
 ,CONSTRAINT FK_PEDIDO_JOGO     FOREIGN KEY (JOGOID)     REFERENCES JOGO     (ID)
 ,CONSTRAINT FK_PEDIDO_PROMOCAO FOREIGN KEY (PROMOCAOID) REFERENCES PROMOCAO (ID)
);
GO




-- PEDIDOS COM PROMOÇÃO 
INSERT INTO PEDIDO (DATACRIACAO, USUARIOID, JOGOID, PROMOCAOID, VLPEDIDO, VLDESCONTO, VLPAGO) VALUES ('2020-07-01 10:00:00', 1, 1,  NULL, 0, 0, 0);
INSERT INTO PEDIDO (DATACRIACAO, USUARIOID, JOGOID, PROMOCAOID, VLPEDIDO, VLDESCONTO, VLPAGO) VALUES ('2022-10-10 14:30:00', 2, 3,  NULL, 0, 0, 0);
INSERT INTO PEDIDO (DATACRIACAO, USUARIOID, JOGOID, PROMOCAOID, VLPEDIDO, VLDESCONTO, VLPAGO) VALUES ('2023-04-01 16:45:00', 3, 4,  NULL, 0, 0, 0);
INSERT INTO PEDIDO (DATACRIACAO, USUARIOID, JOGOID, PROMOCAOID, VLPEDIDO, VLDESCONTO, VLPAGO) VALUES ('2024-01-10 09:20:00', 4, 5,  NULL, 0, 0, 0);
INSERT INTO PEDIDO (DATACRIACAO, USUARIOID, JOGOID, PROMOCAOID, VLPEDIDO, VLDESCONTO, VLPAGO) VALUES ('2025-05-15 11:05:00', 7, 10, NULL, 0, 0, 0);

UPDATE PEDIDO 
SET PROMOCAOID = (SELECT PROMOCAO.ID 
                  FROM PROMOCAO 
                  WHERE PEDIDO.DATACRIACAO BETWEEN  PROMOCAO.DATACRIACAO AND PROMOCAO.DATAVALIDADE);


-- PEDIDOS SEM PROMOÇÃO
INSERT INTO PEDIDO (DATACRIACAO, USUARIOID, JOGOID, PROMOCAOID, VLPEDIDO, VLDESCONTO, VLPAGO) VALUES ('2024-05-01 13:00:00',  8, 7, NULL, 0, 0, 0);
INSERT INTO PEDIDO (DATACRIACAO, USUARIOID, JOGOID, PROMOCAOID, VLPEDIDO, VLDESCONTO, VLPAGO) VALUES ('2023-12-20 20:15:00',  9, 6, NULL, 0, 0, 0);
INSERT INTO PEDIDO (DATACRIACAO, USUARIOID, JOGOID, PROMOCAOID, VLPEDIDO, VLDESCONTO, VLPAGO) VALUES ('2021-07-15 08:50:00',  5, 2, NULL, 0, 0, 0);
INSERT INTO PEDIDO (DATACRIACAO, USUARIOID, JOGOID, PROMOCAOID, VLPEDIDO, VLDESCONTO, VLPAGO) VALUES ('2021-06-01 19:00:00',  6, 8, NULL, 0, 0, 0);
INSERT INTO PEDIDO (DATACRIACAO, USUARIOID, JOGOID, PROMOCAOID, VLPEDIDO, VLDESCONTO, VLPAGO) VALUES ('2023-11-01 17:40:00', 10, 9, NULL, 0, 0, 0);

GO

UPDATE PEDIDO 
SET PEDIDO.VLPEDIDO = ( SELECT JOGO.PRECOBASE
                         FROM JOGO 
                         WHERE JOGO.ID = PEDIDO.JOGOID ) ;
GO


UPDATE PEDIDO 
SET PEDIDO.VLDESCONTO = ROUND(PEDIDO.VLPEDIDO *  ( SELECT CAST(PROMOCAO.DESCONTO AS FLOAT) / 100 
                                                     FROM PROMOCAO 
                                                     WHERE PROMOCAO.ID = PEDIDO.PROMOCAOID ),2)
WHERE PEDIDO.PROMOCAOID > 0;
GO


UPDATE PEDIDO 
SET PEDIDO.VLPAGO = PEDIDO.VLPEDIDO - PEDIDO.VLDESCONTO;

GO


CREATE VIEW VW_PEDIDOS AS
SELECT PEDIDO_ID          = PEDIDO.ID
      ,PEDIDO_DATACRIACAO = PEDIDO.DATACRIACAO
      ,PEDIDO_VLPEDIDO    = PEDIDO.VLPEDIDO
      ,PEDIDO_VLDESCONTO  = PEDIDO.VLDESCONTO
      ,PEDIDO_VLPAGO      = PEDIDO.VLPAGO
      ,USUARIO_ID         = USUARIO.ID
      ,USUARIO_NOME       = USUARIO.NOME
      ,JOGO_ID            = JOGO.ID
      ,JOGO_NOME          = JOGO.NOME
      ,PROMOCAO_ID        = PROMOCAO.ID
      ,PROMOCAO_NOME      = PROMOCAO.NOME
FROM PEDIDO
INNER JOIN USUARIO
  ON USUARIO.ID = PEDIDO.USUARIOID
INNER JOIN JOGO
  ON JOGO.ID = PEDIDO.JOGOID
LEFT JOIN PROMOCAO
  ON PROMOCAO.ID = PEDIDO.PROMOCAOID;

GO